# Generated by Django 5.2.13 on 2026-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lead',
            name='intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='recommended_action',
            field=models.TextField(blank=True, null=True),
        ),
    ]
